"""Add new user fields

Revision ID: 6b1060537f9a
Revises: a01641bb4482
Create Date: 2026-06-23 11:27:03.140865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1060537f9a'
down_revision: Union[str, Sequence[str], None] = 'a01641bb4482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('sessions',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('session_token', sa.String(length=128), nullable=False),
    # sa.Column('user_id', sa.String(length=36), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('expires_at', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('sessions', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_sessions_id'), ['id'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_sessions_session_token'), ['session_token'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('password_salt', sa.String(length=128), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('password_salt')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('username')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # with op.batch_alter_table('sessions', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_sessions_session_token'))
    #     batch_op.drop_index(batch_op.f('ix_sessions_id'))

    # op.drop_table('sessions')
    # ### end Alembic commands ###
