"""Initial schema

Revision ID: 8c5ee59fb187
Revises: 
Create Date: 2026-06-18 12:18:53.696854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5ee59fb187'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ASSET_MANAGER', 'ASSET_CUSTODIAN', 'EMPLOYEE', 'SYSTEM_ADMINISTRATOR', name='userrole', native_enum=False, length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('assets',
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('ICT_EQUIPMENT', 'FURNITURE', 'VEHICLE', 'SOFTWARE', 'OTHER', name='assettype', native_enum=False, length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.Enum('NEW', 'GOOD', 'REFURBISHED', 'DAMAGED', name='assetcondition', native_enum=False, length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'IN_STORAGE', 'UNDER_MAINTENANCE', 'DISPOSED', name='assetstatus', native_enum=False, length=50), nullable=False),
    sa.Column('source_type', sa.Enum('PROCUREMENT', 'DONATION', 'OTHER', name='sourcetype', native_enum=False, length=50), nullable=False),
    sa.Column('procurement_ref', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=False),
    sa.Column('current_custodian_id', sa.String(length=36), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_custodian_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_serial_number'), ['serial_number'], unique=True)

    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_affected', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('assignments',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RETURNED', name='assignmentstatus', native_enum=False, length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('disposal_records',
    sa.Column('disposal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('disposal_date', sa.Date(), nullable=False),
    sa.Column('disposal_method', sa.Enum('SALE', 'WRITE_OFF', 'DONATION', 'DESTRUCTION', name='disposalmethod', native_enum=False, length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('authorised_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['authorised_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('disposal_id')
    )
    op.create_table('maintenance_records',
    sa.Column('maintenance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('service_provider', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.Column('recorded_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('maintenance_id')
    )
    op.create_table('transfers',
    sa.Column('transfer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('from_user_id', sa.String(length=36), nullable=False),
    sa.Column('to_user_id', sa.String(length=36), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('authorised_by', sa.String(length=36), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['authorised_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfers')
    op.drop_table('maintenance_records')
    op.drop_table('disposal_records')
    op.drop_table('assignments')
    op.drop_table('audit_logs')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_serial_number'))

    op.drop_table('assets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
