"""add_user_settings_and_system_settings

Revision ID: b1f2c3d4e5f6
Revises: 6b1060537f9a
Create Date: 2026-06-29 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b1f2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '6b1060537f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notifications_email', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()),
    sa.Column('notifications_in_app', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()),
    sa.Column('notifications_maintenance_alerts', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()),
    sa.Column('notifications_transfer_alerts', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()),
    sa.Column('notifications_request_updates', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()),
    sa.Column('theme', sa.String(length=20), nullable=False, server_default='light'),
    sa.Column('language', sa.String(length=10), nullable=False, server_default='en'),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False, server_default='Uganda Registration Services Bureau'),
    sa.Column('asset_id_prefix', sa.String(length=20), nullable=False, server_default='AST'),
    sa.Column('session_timeout_hours', sa.Integer(), nullable=False, server_default='24'),
    sa.Column('max_failed_logins', sa.Integer(), nullable=False, server_default='3'),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
