export const ICONS = {
  dashboard: "📊",
  assets: "📦",
  add: "➕",
  transfer: "🔄",
  users: "👥",
  audit: "🕐",
  settings: "⚙️",
  request: "📋",
  assignment: "🔑",
  storage: "🏪",
  maintenance: "🔧",
  alert: "⚠️",
  success: "✅",
  error: "❌",
  close: "❌",
  search: "🔍",
  bell: "🔔",
  edit: "✏️",
  delete: "🗑️",
  check: "✔️",
  cancel: "🚫",
  handshake: "🤝",
  return: "↩️",
  calendar: "📅",
  clock: "⏰"
};
