import {
  LayoutDashboard,
  ClipboardList,
  Package,
  Key,
  Archive,
  Repeat,
  Wrench,
  Users,
  History,
  Settings,
  Bell,
  Search,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  CheckCircle2,
  Trash2,
  Clock,
  Building2,
  Eye,
  EyeOff,
  Loader2,
  AlertCircle,
  AlertTriangle,
  X,
  Plus,
  Undo2,
  Menu,
  FileText,
  FileSpreadsheet,
  Layers,
  Copy,
  MoreVertical,
  RefreshCw,
  User,
  Upload,
  File,
  Download,
  File as Document,
  Lock,
  Minus,
} from "lucide-react";
import exportCsvIcon from "../assets/icons8-export-excel-50.png";
import exportPdfIcon from "../assets/icons8-export-pdf-50.png";

export const ICONS = {
  // Navigation / Pages
  dashboard: LayoutDashboard,
  requests: ClipboardList,
  assets: Package,
  inventory: Layers,
  assignments: Key,
  storage: Archive,
  transfers: Repeat,
  maintenance: Wrench,
  users: Users,
  audit: History,
  credentials: Lock,
  settings: Settings,
  
  // File icons
  filePdf: FileText,
  fileXlsx: FileSpreadsheet,

  // UI Utilities
  bell: Bell,
  search: Search,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  checkCircle: CheckCircle2,
  trashCircle: Trash2,
  clock: Clock,
  building: Building2,
  eye: Eye,
  eyeOff: EyeOff,
  spinner: Loader2,
  alertCircle: AlertCircle,
  alert: AlertTriangle,
  close: X,
  plus: Plus,
  add: Plus,
  return: Undo2,
  menu: Menu,
  fileText: FileText,
  fileSpreadsheet: FileSpreadsheet,
  copy: Copy,
  kebab: MoreVertical,
  regenerate: RefreshCw,
  user: User,
  upload: Upload,
  file: File,
  download: Download,
  document: Document,
  minimize: Minus,

  // Keep string mappings of emojis just in case any unmigrated files access them, 
  // though we will migrate all dashboard pages in this pass.
  dashboardEmoji: "📊",
  assetsEmoji: "📦",
  addEmoji: "➕",
  transferEmoji: "🔄",
  usersEmoji: "👥",
  auditEmoji: "🕐",
  settingsEmoji: "⚙️",
  requestEmoji: "📋",
  assignmentEmoji: "🔑",
  storageEmoji: "🏪",
  maintenanceEmoji: "🔧",
  alertEmoji: "⚠️",
  successEmoji: "✅",
  errorEmoji: "❌",
  closeEmoji: "❌",
  searchEmoji: "🔍",
  bellEmoji: "🔔",
  editEmoji: "✏️",
  deleteEmoji: "🗑️",
  checkEmoji: "✔️",
  cancelEmoji: "🚫",
  handshakeEmoji: "🤝",
  returnEmoji: "↩️",
  calendarEmoji: "📅",
  clockEmoji: "⏰",

  // Export Icons
  exportCsvIcon: exportCsvIcon, // Used by the CSV export button on the Assets page
  exportPdfIcon: exportPdfIcon, // Used by the PDF export button on the Assets page
};
